### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by bartandeweg** [notoriousbdg/Home-AssistantConfig#7]
Hello, 

I'm using your package for a while now. Today i've updated to the lastest version and getting errors like the one below. 

Any idea how to handle?: 

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 313, in async_update_ha_state
    self.entity_id, state, attr, self.force_update, self._context)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 853, in async_set
    context)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 623, in __init__
    "State max length is 255 characters.").format(entity_id))
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity id: sensor.fibaro_system_fgms001_motion_sensor_battery_2. State max length is 255 characters.`

**Comment by bartandeweg** [comment]
It that easy ;) Thanks for the reply
